name: Manual Publish Ecosystems
on: workflow_dispatch
jobs:
  publish-ecosystems:
    name: Publish NPM and PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for PyPI trusted publishing
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Publish NPM Package
        working-directory: ./npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python build tools
        run: pip install build twine hatchling

      - name: Build Python Package
        working-directory: ./python
        run: python -m build

      - name: Publish PyPI Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
